// <auto-generated />
using System;
using ElGordo.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ElGordo.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ElGordo.App.Dominio.Detalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("FacturaId")
                        .HasColumnType("int");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<int>("Producto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("ElGordo.App.Dominio.EstadoFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Abreviatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadoFactura");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Aprobada"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Anulada"
                        });
                });

            modelBuilder.Entity("ElGordo.App.Dominio.EstadoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Abreviacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadoPedido");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Realizado"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "En Preparación"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Enviado"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Entregado"
                        });
                });

            modelBuilder.Entity("ElGordo.App.Dominio.EstadoProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Abreviatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("EstadoProducto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Disponible"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "NO Disponible"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Descontinuado"
                        });
                });

            modelBuilder.Entity("ElGordo.App.Dominio.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("ElGordo.App.Dominio.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("Factura")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha_entrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_envio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_pedido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_preparacion")
                        .HasColumnType("datetime2");

                    b.Property<float>("LatitudActual")
                        .HasColumnType("real");

                    b.Property<float>("LatitudEntrega")
                        .HasColumnType("real");

                    b.Property<float>("LongitudActual")
                        .HasColumnType("real");

                    b.Property<float>("LongitudEntrega")
                        .HasColumnType("real");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("ElGordo.App.Dominio.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("ElGordo.App.Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nickname = "admin",
                            Nombre = "Administrador",
                            Password = "admin"
                        });
                });

            modelBuilder.Entity("ElGordo.App.Dominio.Detalle", b =>
                {
                    b.HasOne("ElGordo.App.Dominio.Factura", null)
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId");
                });

            modelBuilder.Entity("ElGordo.App.Dominio.Factura", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
